var crime_stats = [[12,"W","Larceny-Theft"],
[12,"SW","Burglary"],
[12,"SW","Motor Vehicle Theft"],
[12,"SW","Larceny-Theft"],
[12,"SW","Assault"],
[12,"SW","Robbery"],
[12,"SW","Rape"],
[12,"SW","Homicide"],
[12,"SW","Burglary"],
[12,"SW","Motor Vehicle Theft"],
[12,"SW","Larceny-Theft"],
[12,"SW","Assault"],
[12,"SW","Robbery"],
[12,"SW","Rape"],
[12,"SW","Homicide"],
[12,"SW","Burglary"],
[12,"SW","Motor Vehicle Theft"],
[12,"SW","Larceny-Theft"],
[12,"SW","Assault"],
[12,"SW","Robbery"],
[12,"SW","Rape"],
[12,"SW","Homicide"],
[12,"SW","Burglary"],
[12,"SW","Motor Vehicle Theft"],
[12,"SW","Larceny-Theft"],
[12,"SW","Assault"],
[12,"SW","Robbery"],
[12,"SW","Rape"],
[12,"SW","Homicide"],
[12,"SW","Burglary"],
[12,"SW","Motor Vehicle Theft"],
[12,"SW","Larceny-Theft"],
[12,"SW","Assault"],
[12,"SW","Robbery"],
[12,"SW","Rape"],
[12,"SW","Homicide"],
[12,"SW","Burglary"],
[12,"SW","Motor Vehicle Theft"],
[12,"SW","Larceny-Theft"],
[12,"SW","Assault"],
[12,"SW","Robbery"],
[12,"SW","Rape"],
[12,"SW","Homicide"],
[12,"SE","Burglary"],
[12,"SE","Motor Vehicle Theft"],
[12,"SE","Larceny-Theft"],
[12,"SE","Assault"],
[12,"SE","Robbery"],
[12,"SE","Rape"],
[12,"SE","Homicide"],
[12,"SE","Burglary"],
[12,"SE","Motor Vehicle Theft"],
[12,"SE","Larceny-Theft"],
[12,"SE","Assault"],
[12,"SE","Robbery"],
[12,"SE","Rape"],
[12,"SE","Homicide"],
[12,"SE","Burglary"],
[12,"SE","Motor Vehicle Theft"],
[12,"SE","Larceny-Theft"],
[12,"SE","Assault"],
[12,"SE","Robbery"],
[12,"SE","Rape"],
[12,"SE","Homicide"],
[12,"SE","Burglary"],
[12,"SE","Motor Vehicle Theft"],
[12,"SE","Larceny-Theft"],
[12,"SE","Assault"],
[12,"SE","Robbery"],
[12,"SE","Rape"],
[12,"SE","Homicide"],
[12,"SE","Burglary"],
[12,"SE","Motor Vehicle Theft"],
[12,"SE","Larceny-Theft"],
[12,"SE","Assault"],
[12,"SE","Robbery"],
[12,"SE","Rape"],
[12,"SE","Homicide"],
[12,"SE","Burglary"],
[12,"SE","Motor Vehicle Theft"],
[12,"SE","Larceny-Theft"],
[12,"SE","Assault"],
[12,"SE","Robbery"],
[12,"SE","Rape"],
[12,"SE","Homicide"],
[12,"SE","Burglary"],
[12,"SE","Motor Vehicle Theft"],
[12,"SE","Larceny-Theft"],
[12,"SE","Assault"],
[12,"SE","Robbery"],
[12,"SE","Rape"],
[12,"SE","Homicide"],
[12,"SE","Burglary"],
[12,"SE","Motor Vehicle Theft"],
[12,"SE","Larceny-Theft"],
[12,"SE","Assault"],
[12,"SE","Robbery"],
[12,"SE","Rape"],
[12,"SE","Homicide"],
[12,"SE","Burglary"],
[12,"SE","Motor Vehicle Theft"],
[12,"SE","Larceny-Theft"],
[12,"SE","Assault"],
[12,"SE","Robbery"],
[12,"SE","Rape"],
[12,"SE","Homicide"],
[12,"E","Burglary"],
[12,"E","Motor Vehicle Theft"],
[12,"E","Larceny-Theft"],
[12,"E","Assault"],
[12,"E","Robbery"],
[12,"E","Rape"],
[12,"E","Homicide"],
[12,"E","Burglary"],
[12,"E","Motor Vehicle Theft"],
[12,"E","Larceny-Theft"],
[12,"E","Assault"],
[12,"E","Robbery"],
[12,"E","Rape"],
[12,"E","Homicide"],
[12,"E","Burglary"],
[12,"E","Motor Vehicle Theft"],
[12,"E","Larceny-Theft"],
[12,"E","Assault"],
[12,"E","Robbery"],
[12,"E","Rape"],
[12,"E","Homicide"],
[12,"E","Burglary"],
[12,"E","Motor Vehicle Theft"],
[12,"E","Larceny-Theft"],
[12,"E","Assault"],
[12,"E","Robbery"],
[12,"E","Rape"],
[12,"E","Homicide"],
[12,"E","Burglary"],
[12,"E","Motor Vehicle Theft"],
[12,"E","Larceny-Theft"],
[12,"E","Assault"],
[12,"E","Robbery"],
[12,"E","Rape"],
[12,"E","Homicide"],
[12,"E","Burglary"],
[12,"E","Motor Vehicle Theft"],
[12,"E","Larceny-Theft"],
[12,"E","Assault"],
[12,"E","Robbery"],
[12,"E","Rape"],
[12,"E","Homicide"],
[12,"E","Burglary"],
[12,"E","Motor Vehicle Theft"],
[12,"E","Larceny-Theft"],
[12,"E","Assault"],
[12,"E","Robbery"],
[12,"E","Rape"],
[12,"E","Homicide"],
[12,"E","Burglary"],
[12,"E","Motor Vehicle Theft"],
[12,"E","Larceny-Theft"],
[12,"E","Assault"],
[12,"E","Robbery"],
[12,"E","Rape"],
[12,"E","Homicide"],
[12,"E","Burglary"],
[12,"E","Motor Vehicle Theft"],
[12,"E","Larceny-Theft"],
[12,"E","Assault"],
[12,"E","Robbery"],
[12,"E","Rape"],
[12,"E","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"W","Burglary"],
[12,"W","Motor Vehicle Theft"],
[12,"W","Larceny-Theft"],
[12,"W","Assault"],
[12,"W","Robbery"],
[12,"W","Rape"],
[12,"W","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[12,"N","Burglary"],
[12,"N","Motor Vehicle Theft"],
[12,"N","Larceny-Theft"],
[12,"N","Assault"],
[12,"N","Robbery"],
[12,"N","Rape"],
[12,"N","Homicide"],
[11,"N","Rape"],
[11,"SW","Burglary"],
[11,"SW","Motor Vehicle Theft"],
[11,"SW","Larceny-Theft"],
[11,"SW","Assault"],
[11,"SW","Robbery"],
[11,"SW","Rape"],
[11,"SW","Homicide"],
[11,"SW","Burglary"],
[11,"SW","Motor Vehicle Theft"],
[11,"SW","Larceny-Theft"],
[11,"SW","Assault"],
[11,"SW","Robbery"],
[11,"SW","Rape"],
[11,"SW","Homicide"],
[11,"SW","Burglary"],
[11,"SW","Motor Vehicle Theft"],
[11,"SW","Larceny-Theft"],
[11,"SW","Assault"],
[11,"SW","Robbery"],
[11,"SW","Rape"],
[11,"SW","Homicide"],
[11,"SW","Burglary"],
[11,"SW","Motor Vehicle Theft"],
[11,"SW","Larceny-Theft"],
[11,"SW","Assault"],
[11,"SW","Robbery"],
[11,"SW","Rape"],
[11,"SW","Homicide"],
[11,"SW","Burglary"],
[11,"SW","Motor Vehicle Theft"],
[11,"SW","Larceny-Theft"],
[11,"SW","Assault"],
[11,"SW","Robbery"],
[11,"SW","Rape"],
[11,"SW","Homicide"],
[11,"SW","Burglary"],
[11,"SW","Motor Vehicle Theft"],
[11,"SW","Larceny-Theft"],
[11,"SW","Assault"],
[11,"SW","Robbery"],
[11,"SW","Rape"],
[11,"SW","Homicide"],
[11,"SE","Burglary"],
[11,"SE","Motor Vehicle Theft"],
[11,"SE","Larceny-Theft"],
[11,"SE","Assault"],
[11,"SE","Robbery"],
[11,"SE","Rape"],
[11,"SE","Homicide"],
[11,"SE","Burglary"],
[11,"SE","Motor Vehicle Theft"],
[11,"SE","Larceny-Theft"],
[11,"SE","Assault"],
[11,"SE","Robbery"],
[11,"SE","Rape"],
[11,"SE","Homicide"],
[11,"SE","Burglary"],
[11,"SE","Motor Vehicle Theft"],
[11,"SE","Larceny-Theft"],
[11,"SE","Assault"],
[11,"SE","Robbery"],
[11,"SE","Rape"],
[11,"SE","Homicide"],
[11,"SE","Burglary"],
[11,"SE","Motor Vehicle Theft"],
[11,"SE","Larceny-Theft"],
[11,"SE","Assault"],
[11,"SE","Robbery"],
[11,"SE","Rape"],
[11,"SE","Homicide"],
[11,"SE","Burglary"],
[11,"SE","Motor Vehicle Theft"],
[11,"SE","Larceny-Theft"],
[11,"SE","Assault"],
[11,"SE","Robbery"],
[11,"SE","Rape"],
[11,"SE","Homicide"],
[11,"SE","Burglary"],
[11,"SE","Motor Vehicle Theft"],
[11,"SE","Larceny-Theft"],
[11,"SE","Assault"],
[11,"SE","Robbery"],
[11,"SE","Rape"],
[11,"SE","Homicide"],
[11,"SE","Burglary"],
[11,"SE","Motor Vehicle Theft"],
[11,"SE","Larceny-Theft"],
[11,"SE","Assault"],
[11,"SE","Robbery"],
[11,"SE","Rape"],
[11,"SE","Homicide"],
[11,"SE","Burglary"],
[11,"SE","Motor Vehicle Theft"],
[11,"SE","Larceny-Theft"],
[11,"SE","Assault"],
[11,"SE","Robbery"],
[11,"SE","Rape"],
[11,"SE","Homicide"],
[11,"SE","Burglary"],
[11,"SE","Motor Vehicle Theft"],
[11,"SE","Larceny-Theft"],
[11,"SE","Assault"],
[11,"SE","Robbery"],
[11,"SE","Rape"],
[11,"SE","Homicide"],
[11,"E","Burglary"],
[11,"E","Motor Vehicle Theft"],
[11,"E","Larceny-Theft"],
[11,"E","Assault"],
[11,"E","Robbery"],
[11,"E","Rape"],
[11,"E","Homicide"],
[11,"E","Burglary"],
[11,"E","Motor Vehicle Theft"],
[11,"E","Larceny-Theft"],
[11,"E","Assault"],
[11,"E","Robbery"],
[11,"E","Rape"],
[11,"E","Homicide"],
[11,"E","Burglary"],
[11,"E","Motor Vehicle Theft"],
[11,"E","Larceny-Theft"],
[11,"E","Assault"],
[11,"E","Robbery"],
[11,"E","Rape"],
[11,"E","Homicide"],
[11,"E","Burglary"],
[11,"E","Motor Vehicle Theft"],
[11,"E","Larceny-Theft"],
[11,"E","Assault"],
[11,"E","Robbery"],
[11,"E","Rape"],
[11,"E","Homicide"],
[11,"E","Burglary"],
[11,"E","Motor Vehicle Theft"],
[11,"E","Larceny-Theft"],
[11,"E","Assault"],
[11,"E","Robbery"],
[11,"E","Rape"],
[11,"E","Homicide"],
[11,"E","Burglary"],
[11,"E","Motor Vehicle Theft"],
[11,"E","Larceny-Theft"],
[11,"E","Assault"],
[11,"E","Robbery"],
[11,"E","Rape"],
[11,"E","Homicide"],
[11,"E","Burglary"],
[11,"E","Motor Vehicle Theft"],
[11,"E","Larceny-Theft"],
[11,"E","Assault"],
[11,"E","Robbery"],
[11,"E","Rape"],
[11,"E","Homicide"],
[11,"E","Burglary"],
[11,"E","Motor Vehicle Theft"],
[11,"E","Larceny-Theft"],
[11,"E","Assault"],
[11,"E","Robbery"],
[11,"E","Rape"],
[11,"E","Homicide"],
[11,"E","Burglary"],
[11,"E","Motor Vehicle Theft"],
[11,"E","Larceny-Theft"],
[11,"E","Assault"],
[11,"E","Robbery"],
[11,"E","Rape"],
[11,"E","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"N","Homicide"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"W","Burglary"],
[11,"W","Motor Vehicle Theft"],
[11,"W","Larceny-Theft"],
[11,"W","Assault"],
[11,"W","Robbery"],
[11,"W","Rape"],
[11,"W","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[11,"N","Rape"],
[11,"N","Homicide"],
[11,"N","Burglary"],
[11,"N","Motor Vehicle Theft"],
[11,"N","Larceny-Theft"],
[11,"N","Assault"],
[11,"N","Robbery"],
[10,"W","Motor Vehicle Theft"],
[10,"SW","Burglary"],
[10,"SW","Motor Vehicle Theft"],
[10,"SW","Larceny-Theft"],
[10,"SW","Assault"],
[10,"SW","Robbery"],
[10,"SW","Rape"],
[10,"SW","Homicide"],
[10,"SW","Burglary"],
[10,"SW","Motor Vehicle Theft"],
[10,"SW","Larceny-Theft"],
[10,"SW","Assault"],
[10,"SW","Robbery"],
[10,"SW","Rape"],
[10,"SW","Homicide"],
[10,"SW","Burglary"],
[10,"SW","Motor Vehicle Theft"],
[10,"SW","Larceny-Theft"],
[10,"SW","Assault"],
[10,"SW","Robbery"],
[10,"SW","Rape"],
[10,"SW","Homicide"],
[10,"SW","Burglary"],
[10,"SW","Motor Vehicle Theft"],
[10,"SW","Larceny-Theft"],
[10,"SW","Assault"],
[10,"SW","Robbery"],
[10,"SW","Rape"],
[10,"SW","Homicide"],
[10,"SW","Burglary"],
[10,"SW","Motor Vehicle Theft"],
[10,"SW","Larceny-Theft"],
[10,"SW","Assault"],
[10,"SW","Robbery"],
[10,"SW","Rape"],
[10,"SW","Homicide"],
[10,"SW","Burglary"],
[10,"SW","Motor Vehicle Theft"],
[10,"SW","Larceny-Theft"],
[10,"SW","Assault"],
[10,"SW","Robbery"],
[10,"SW","Rape"],
[10,"SW","Homicide"],
[10,"SE","Burglary"],
[10,"SE","Motor Vehicle Theft"],
[10,"SE","Larceny-Theft"],
[10,"SE","Assault"],
[10,"SE","Robbery"],
[10,"SE","Rape"],
[10,"SE","Homicide"],
[10,"SE","Burglary"],
[10,"SE","Motor Vehicle Theft"],
[10,"SE","Larceny-Theft"],
[10,"SE","Assault"],
[10,"SE","Robbery"],
[10,"SE","Rape"],
[10,"SE","Homicide"],
[10,"SE","Burglary"],
[10,"SE","Motor Vehicle Theft"],
[10,"SE","Larceny-Theft"],
[10,"SE","Assault"],
[10,"SE","Robbery"],
[10,"SE","Rape"],
[10,"SE","Homicide"],
[10,"SE","Burglary"],
[10,"SE","Motor Vehicle Theft"],
[10,"SE","Larceny-Theft"],
[10,"SE","Assault"],
[10,"SE","Robbery"],
[10,"SE","Rape"],
[10,"SE","Homicide"],
[10,"SE","Burglary"],
[10,"SE","Motor Vehicle Theft"],
[10,"SE","Larceny-Theft"],
[10,"SE","Assault"],
[10,"SE","Robbery"],
[10,"SE","Rape"],
[10,"SE","Homicide"],
[10,"SE","Burglary"],
[10,"SE","Motor Vehicle Theft"],
[10,"SE","Larceny-Theft"],
[10,"SE","Assault"],
[10,"SE","Robbery"],
[10,"SE","Rape"],
[10,"SE","Homicide"],
[10,"SE","Burglary"],
[10,"SE","Motor Vehicle Theft"],
[10,"SE","Larceny-Theft"],
[10,"SE","Assault"],
[10,"SE","Robbery"],
[10,"SE","Rape"],
[10,"SE","Homicide"],
[10,"SE","Burglary"],
[10,"SE","Motor Vehicle Theft"],
[10,"SE","Larceny-Theft"],
[10,"SE","Assault"],
[10,"SE","Robbery"],
[10,"SE","Rape"],
[10,"SE","Homicide"],
[10,"SE","Burglary"],
[10,"SE","Motor Vehicle Theft"],
[10,"SE","Larceny-Theft"],
[10,"SE","Assault"],
[10,"SE","Robbery"],
[10,"SE","Rape"],
[10,"SE","Homicide"],
[10,"E","Burglary"],
[10,"E","Motor Vehicle Theft"],
[10,"E","Larceny-Theft"],
[10,"E","Assault"],
[10,"E","Robbery"],
[10,"E","Rape"],
[10,"E","Homicide"],
[10,"E","Burglary"],
[10,"E","Motor Vehicle Theft"],
[10,"E","Larceny-Theft"],
[10,"E","Assault"],
[10,"E","Robbery"],
[10,"E","Rape"],
[10,"E","Homicide"],
[10,"E","Burglary"],
[10,"E","Motor Vehicle Theft"],
[10,"E","Larceny-Theft"],
[10,"E","Assault"],
[10,"E","Robbery"],
[10,"E","Rape"],
[10,"E","Homicide"],
[10,"E","Burglary"],
[10,"E","Motor Vehicle Theft"],
[10,"E","Larceny-Theft"],
[10,"E","Assault"],
[10,"E","Robbery"],
[10,"E","Rape"],
[10,"E","Homicide"],
[10,"E","Burglary"],
[10,"E","Motor Vehicle Theft"],
[10,"E","Larceny-Theft"],
[10,"E","Assault"],
[10,"E","Robbery"],
[10,"E","Rape"],
[10,"E","Homicide"],
[10,"E","Burglary"],
[10,"E","Motor Vehicle Theft"],
[10,"E","Larceny-Theft"],
[10,"E","Assault"],
[10,"E","Robbery"],
[10,"E","Rape"],
[10,"E","Homicide"],
[10,"E","Burglary"],
[10,"E","Motor Vehicle Theft"],
[10,"E","Motor Vehicle Theft"],
[10,"E","Larceny-Theft"],
[10,"E","Assault"],
[10,"E","Robbery"],
[10,"E","Rape"],
[10,"E","Homicide"],
[10,"E","Burglary"],
[10,"E","Motor Vehicle Theft"],
[10,"E","Larceny-Theft"],
[10,"E","Assault"],
[10,"E","Robbery"],
[10,"E","Rape"],
[10,"E","Homicide"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"W","Burglary"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Homicide"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"W","Burglary"],
[10,"W","Motor Vehicle Theft"],
[10,"W","Larceny-Theft"],
[10,"W","Assault"],
[10,"W","Robbery"],
[10,"W","Rape"],
[10,"W","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"N","Burglary"],
[10,"N","Motor Vehicle Theft"],
[10,"N","Larceny-Theft"],
[10,"N","Assault"],
[10,"N","Robbery"],
[10,"N","Rape"],
[10,"N","Homicide"],
[10,"E","Larceny-Theft"],
[10,"E","Assault"],
[10,"E","Robbery"],
[10,"E","Rape"],
[10,"E","Homicide"],
[10,"E","Burglary"],
[10,"W","Larceny-Theft"],
[9,"W","Larceny-Theft"],
[9,"SW","Burglary"],
[9,"SW","Motor Vehicle Theft"],
[9,"SW","Larceny-Theft"],
[9,"SW","Assault"],
[9,"SW","Robbery"],
[9,"SW","Rape"],
[9,"SW","Homicide"],
[9,"SW","Burglary"],
[9,"SW","Motor Vehicle Theft"],
[9,"SW","Larceny-Theft"],
[9,"SW","Assault"],
[9,"SW","Robbery"],
[9,"SW","Rape"],
[9,"SW","Homicide"],
[9,"SW","Burglary"],
[9,"SW","Motor Vehicle Theft"],
[9,"SW","Larceny-Theft"],
[9,"SW","Assault"],
[9,"SW","Robbery"],
[9,"SW","Rape"],
[9,"SW","Homicide"],
[9,"SW","Burglary"],
[9,"SW","Motor Vehicle Theft"],
[9,"SW","Larceny-Theft"],
[9,"SW","Assault"],
[9,"SW","Robbery"],
[9,"SW","Rape"],
[9,"SW","Homicide"],
[9,"SW","Burglary"],
[9,"SW","Motor Vehicle Theft"],
[9,"SW","Larceny-Theft"],
[9,"SW","Assault"],
[9,"SW","Robbery"],
[9,"SW","Rape"],
[9,"SW","Homicide"],
[9,"SW","Burglary"],
[9,"SW","Motor Vehicle Theft"],
[9,"SW","Larceny-Theft"],
[9,"SW","Assault"],
[9,"SW","Robbery"],
[9,"SW","Rape"],
[9,"SW","Homicide"],
[9,"SE","Burglary"],
[9,"SE","Motor Vehicle Theft"],
[9,"SE","Larceny-Theft"],
[9,"SE","Assault"],
[9,"SE","Robbery"],
[9,"SE","Rape"],
[9,"SE","Homicide"],
[9,"SE","Burglary"],
[9,"SE","Motor Vehicle Theft"],
[9,"SE","Larceny-Theft"],
[9,"SE","Assault"],
[9,"SE","Robbery"],
[9,"SE","Rape"],
[9,"SE","Homicide"],
[9,"SE","Burglary"],
[9,"SE","Motor Vehicle Theft"],
[9,"SE","Larceny-Theft"],
[9,"SE","Assault"],
[9,"SE","Robbery"],
[9,"SE","Rape"],
[9,"SE","Homicide"],
[9,"SE","Burglary"],
[9,"SE","Motor Vehicle Theft"],
[9,"SE","Larceny-Theft"],
[9,"SE","Assault"],
[9,"SE","Robbery"],
[9,"SE","Rape"],
[9,"SE","Homicide"],
[9,"SE","Burglary"],
[9,"SE","Motor Vehicle Theft"],
[9,"SE","Larceny-Theft"],
[9,"SE","Assault"],
[9,"SE","Robbery"],
[9,"SE","Rape"],
[9,"SE","Homicide"],
[9,"SE","Burglary"],
[9,"SE","Motor Vehicle Theft"],
[9,"SE","Larceny-Theft"],
[9,"SE","Assault"],
[9,"SE","Robbery"],
[9,"SE","Rape"],
[9,"SE","Homicide"],
[9,"SE","Burglary"],
[9,"SE","Motor Vehicle Theft"],
[9,"SE","Larceny-Theft"],
[9,"SE","Assault"],
[9,"SE","Robbery"],
[9,"SE","Rape"],
[9,"SE","Homicide"],
[9,"SE","Burglary"],
[9,"SE","Motor Vehicle Theft"],
[9,"SE","Larceny-Theft"],
[9,"SE","Assault"],
[9,"SE","Robbery"],
[9,"SE","Rape"],
[9,"SE","Homicide"],
[9,"SE","Burglary"],
[9,"SE","Motor Vehicle Theft"],
[9,"SE","Larceny-Theft"],
[9,"SE","Assault"],
[9,"SE","Robbery"],
[9,"SE","Rape"],
[9,"SE","Homicide"],
[9,"E","Burglary"],
[9,"E","Motor Vehicle Theft"],
[9,"E","Larceny-Theft"],
[9,"E","Assault"],
[9,"E","Robbery"],
[9,"E","Rape"],
[9,"E","Homicide"],
[9,"E","Burglary"],
[9,"E","Motor Vehicle Theft"],
[9,"E","Larceny-Theft"],
[9,"E","Assault"],
[9,"E","Robbery"],
[9,"E","Rape"],
[9,"E","Homicide"],
[9,"E","Burglary"],
[9,"E","Motor Vehicle Theft"],
[9,"E","Larceny-Theft"],
[9,"E","Assault"],
[9,"E","Robbery"],
[9,"E","Rape"],
[9,"E","Homicide"],
[9,"E","Burglary"],
[9,"E","Motor Vehicle Theft"],
[9,"E","Larceny-Theft"],
[9,"E","Assault"],
[9,"E","Robbery"],
[9,"E","Rape"],
[9,"E","Homicide"],
[9,"E","Burglary"],
[9,"E","Motor Vehicle Theft"],
[9,"E","Larceny-Theft"],
[9,"E","Assault"],
[9,"E","Robbery"],
[9,"E","Rape"],
[9,"E","Homicide"],
[9,"E","Burglary"],
[9,"E","Motor Vehicle Theft"],
[9,"E","Larceny-Theft"],
[9,"E","Assault"],
[9,"E","Robbery"],
[9,"E","Rape"],
[9,"E","Homicide"],
[9,"E","Burglary"],
[9,"E","Motor Vehicle Theft"],
[9,"E","Larceny-Theft"],
[9,"E","Assault"],
[9,"E","Robbery"],
[9,"E","Rape"],
[9,"E","Homicide"],
[9,"E","Burglary"],
[9,"E","Motor Vehicle Theft"],
[9,"E","Larceny-Theft"],
[9,"E","Assault"],
[9,"E","Robbery"],
[9,"E","Rape"],
[9,"E","Homicide"],
[9,"E","Burglary"],
[9,"E","Motor Vehicle Theft"],
[9,"E","Larceny-Theft"],
[9,"E","Assault"],
[9,"E","Robbery"],
[9,"E","Rape"],
[9,"E","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"W","Burglary"],
[9,"W","Motor Vehicle Theft"],
[9,"W","Larceny-Theft"],
[9,"W","Assault"],
[9,"W","Robbery"],
[9,"W","Rape"],
[9,"W","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[9,"N","Burglary"],
[9,"N","Motor Vehicle Theft"],
[9,"N","Larceny-Theft"],
[9,"N","Assault"],
[9,"N","Robbery"],
[9,"N","Rape"],
[9,"N","Homicide"],
[8,"N","Robbery"],
[8,"SW","Burglary"],
[8,"SW","Motor Vehicle Theft"],
[8,"SW","Larceny-Theft"],
[8,"SW","Assault"],
[8,"SW","Robbery"],
[8,"SW","Rape"],
[8,"SW","Homicide"],
[8,"SW","Burglary"],
[8,"SW","Motor Vehicle Theft"],
[8,"SW","Larceny-Theft"],
[8,"SW","Assault"],
[8,"SW","Robbery"],
[8,"SW","Rape"],
[8,"SW","Homicide"],
[8,"SW","Burglary"],
[8,"SW","Motor Vehicle Theft"],
[8,"SW","Larceny-Theft"],
[8,"SW","Assault"],
[8,"SW","Robbery"],
[8,"SW","Rape"],
[8,"SW","Homicide"],
[8,"SW","Burglary"],
[8,"SW","Motor Vehicle Theft"],
[8,"SW","Larceny-Theft"],
[8,"SW","Assault"],
[8,"SW","Robbery"],
[8,"SW","Rape"],
[8,"SW","Homicide"],
[8,"SW","Burglary"],
[8,"SW","Motor Vehicle Theft"],
[8,"SW","Larceny-Theft"],
[8,"SW","Assault"],
[8,"SW","Robbery"],
[8,"SW","Rape"],
[8,"SW","Homicide"],
[8,"SW","Burglary"],
[8,"SW","Motor Vehicle Theft"],
[8,"SW","Larceny-Theft"],
[8,"SW","Assault"],
[8,"SW","Robbery"],
[8,"SW","Rape"],
[8,"SW","Homicide"],
[8,"SE","Burglary"],
[8,"SE","Motor Vehicle Theft"],
[8,"SE","Larceny-Theft"],
[8,"SE","Assault"],
[8,"SE","Robbery"],
[8,"SE","Rape"],
[8,"SE","Homicide"],
[8,"SE","Burglary"],
[8,"SE","Motor Vehicle Theft"],
[8,"SE","Larceny-Theft"],
[8,"SE","Assault"],
[8,"SE","Robbery"],
[8,"SE","Rape"],
[8,"SE","Homicide"],
[8,"SE","Burglary"],
[8,"SE","Motor Vehicle Theft"],
[8,"SE","Larceny-Theft"],
[8,"SE","Assault"],
[8,"SE","Robbery"],
[8,"SE","Rape"],
[8,"SE","Homicide"],
[8,"SE","Burglary"],
[8,"SE","Motor Vehicle Theft"],
[8,"SE","Larceny-Theft"],
[8,"SE","Assault"],
[8,"SE","Robbery"],
[8,"SE","Rape"],
[8,"SE","Homicide"],
[8,"SE","Burglary"],
[8,"SE","Motor Vehicle Theft"],
[8,"SE","Larceny-Theft"],
[8,"SE","Assault"],
[8,"SE","Robbery"],
[8,"SE","Rape"],
[8,"SE","Homicide"],
[8,"SE","Burglary"],
[8,"SE","Motor Vehicle Theft"],
[8,"SE","Larceny-Theft"],
[8,"SE","Assault"],
[8,"SE","Robbery"],
[8,"SE","Rape"],
[8,"SE","Homicide"],
[8,"SE","Burglary"],
[8,"SE","Motor Vehicle Theft"],
[8,"SE","Larceny-Theft"],
[8,"SE","Assault"],
[8,"SE","Robbery"],
[8,"SE","Rape"],
[8,"SE","Homicide"],
[8,"SE","Burglary"],
[8,"SE","Motor Vehicle Theft"],
[8,"SE","Larceny-Theft"],
[8,"SE","Assault"],
[8,"SE","Robbery"],
[8,"SE","Rape"],
[8,"SE","Homicide"],
[8,"SE","Burglary"],
[8,"SE","Motor Vehicle Theft"],
[8,"SE","Larceny-Theft"],
[8,"SE","Assault"],
[8,"SE","Robbery"],
[8,"SE","Rape"],
[8,"SE","Homicide"],
[8,"E","Burglary"],
[8,"E","Motor Vehicle Theft"],
[8,"E","Larceny-Theft"],
[8,"E","Assault"],
[8,"E","Robbery"],
[8,"E","Rape"],
[8,"E","Homicide"],
[8,"E","Burglary"],
[8,"E","Motor Vehicle Theft"],
[8,"E","Larceny-Theft"],
[8,"E","Assault"],
[8,"E","Robbery"],
[8,"E","Rape"],
[8,"E","Homicide"],
[8,"E","Burglary"],
[8,"E","Motor Vehicle Theft"],
[8,"E","Larceny-Theft"],
[8,"E","Assault"],
[8,"E","Robbery"],
[8,"E","Rape"],
[8,"E","Homicide"],
[8,"E","Burglary"],
[8,"E","Motor Vehicle Theft"],
[8,"E","Larceny-Theft"],
[8,"E","Assault"],
[8,"E","Robbery"],
[8,"E","Rape"],
[8,"E","Homicide"],
[8,"E","Burglary"],
[8,"E","Motor Vehicle Theft"],
[8,"E","Larceny-Theft"],
[8,"E","Assault"],
[8,"E","Robbery"],
[8,"E","Rape"],
[8,"E","Homicide"],
[8,"E","Burglary"],
[8,"E","Motor Vehicle Theft"],
[8,"E","Larceny-Theft"],
[8,"E","Assault"],
[8,"E","Robbery"],
[8,"E","Rape"],
[8,"E","Homicide"],
[8,"E","Burglary"],
[8,"E","Motor Vehicle Theft"],
[8,"E","Larceny-Theft"],
[8,"E","Assault"],
[8,"E","Robbery"],
[8,"E","Rape"],
[8,"E","Homicide"],
[8,"E","Burglary"],
[8,"E","Motor Vehicle Theft"],
[8,"E","Larceny-Theft"],
[8,"E","Assault"],
[8,"E","Robbery"],
[8,"E","Rape"],
[8,"E","Homicide"],
[8,"E","Burglary"],
[8,"E","Motor Vehicle Theft"],
[8,"E","Larceny-Theft"],
[8,"E","Assault"],
[8,"E","Robbery"],
[8,"E","Rape"],
[8,"E","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"W","Burglary"],
[8,"W","Motor Vehicle Theft"],
[8,"W","Larceny-Theft"],
[8,"W","Assault"],
[8,"W","Robbery"],
[8,"W","Rape"],
[8,"W","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[8,"N","Robbery"],
[8,"N","Rape"],
[8,"N","Homicide"],
[8,"N","Burglary"],
[8,"N","Motor Vehicle Theft"],
[8,"N","Larceny-Theft"],
[8,"N","Assault"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"N","Homicide"],
[7,"N","Rape"],
[7,"N","Robbery"],
[7,"N","Assault"],
[7,"N","Larceny-Theft"],
[7,"N","Motor Vehicle Theft"],
[7,"N","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"W","Homicide"],
[7,"W","Rape"],
[7,"W","Robbery"],
[7,"W","Assault"],
[7,"W","Larceny-Theft"],
[7,"W","Motor Vehicle Theft"],
[7,"W","Burglary"],
[7,"E","Homicide"],
[7,"E","Rape"],
[7,"E","Robbery"],
[7,"E","Assault"],
[7,"E","Larceny-Theft"],
[7,"E","Motor Vehicle Theft"],
[7,"E","Burglary"],
[7,"E","Homicide"],
[7,"E","Rape"],
[7,"E","Robbery"],
[7,"E","Assault"],
[7,"E","Larceny-Theft"],
[7,"E","Motor Vehicle Theft"],
[7,"E","Burglary"],
[7,"E","Homicide"],
[7,"E","Rape"],
[7,"E","Robbery"],
[7,"E","Assault"],
[7,"E","Larceny-Theft"],
[7,"E","Motor Vehicle Theft"],
[7,"E","Burglary"],
[7,"E","Homicide"],
[7,"E","Rape"],
[7,"E","Robbery"],
[7,"E","Assault"],
[7,"E","Larceny-Theft"],
[7,"E","Motor Vehicle Theft"],
[7,"E","Burglary"],
[7,"E","Homicide"],
[7,"E","Rape"],
[7,"E","Robbery"],
[7,"E","Assault"],
[7,"E","Larceny-Theft"],
[7,"E","Motor Vehicle Theft"],
[7,"E","Burglary"],
[7,"E","Homicide"],
[7,"E","Rape"],
[7,"E","Robbery"],
[7,"E","Assault"],
[7,"E","Larceny-Theft"],
[7,"E","Motor Vehicle Theft"],
[7,"E","Burglary"],
[7,"E","Homicide"],
[7,"E","Rape"],
[7,"E","Robbery"],
[7,"E","Assault"],
[7,"E","Larceny-Theft"],
[7,"E","Motor Vehicle Theft"],
[7,"E","Burglary"],
[7,"E","Homicide"],
[7,"E","Rape"],
[7,"E","Robbery"],
[7,"E","Assault"],
[7,"E","Larceny-Theft"],
[7,"E","Motor Vehicle Theft"],
[7,"E","Burglary"],
[7,"E","Homicide"],
[7,"E","Rape"],
[7,"E","Robbery"],
[7,"E","Assault"],
[7,"E","Larceny-Theft"],
[7,"E","Motor Vehicle Theft"],
[7,"E","Burglary"],
[7,"SE","Homicide"],
[7,"SE","Rape"],
[7,"SE","Robbery"],
[7,"SE","Assault"],
[7,"SE","Larceny-Theft"],
[7,"SE","Motor Vehicle Theft"],
[7,"SE","Burglary"],
[7,"SE","Homicide"],
[7,"SE","Rape"],
[7,"SE","Robbery"],
[7,"SE","Assault"],
[7,"SE","Larceny-Theft"],
[7,"SE","Motor Vehicle Theft"],
[7,"SE","Burglary"],
[7,"SE","Homicide"],
[7,"SE","Rape"],
[7,"SE","Robbery"],
[7,"SE","Assault"],
[7,"SE","Larceny-Theft"],
[7,"SE","Motor Vehicle Theft"],
[7,"SE","Burglary"],
[7,"SE","Homicide"],
[7,"SE","Rape"],
[7,"SE","Robbery"],
[7,"SE","Assault"],
[7,"SE","Larceny-Theft"],
[7,"SE","Motor Vehicle Theft"],
[7,"SE","Burglary"],
[7,"SE","Homicide"],
[7,"SE","Rape"],
[7,"SE","Robbery"],
[7,"SE","Assault"],
[7,"SE","Larceny-Theft"],
[7,"SE","Motor Vehicle Theft"],
[7,"SE","Burglary"],
[7,"SE","Homicide"],
[7,"SE","Rape"],
[7,"SE","Robbery"],
[7,"SE","Assault"],
[7,"SE","Larceny-Theft"],
[7,"SE","Motor Vehicle Theft"],
[7,"SE","Burglary"],
[7,"SE","Homicide"],
[7,"SE","Rape"],
[7,"SE","Robbery"],
[7,"SE","Assault"],
[7,"SE","Larceny-Theft"],
[7,"SE","Motor Vehicle Theft"],
[7,"SE","Burglary"],
[7,"SE","Homicide"],
[7,"SE","Rape"],
[7,"SE","Robbery"],
[7,"SE","Assault"],
[7,"SE","Larceny-Theft"],
[7,"SE","Motor Vehicle Theft"],
[7,"SE","Burglary"],
[7,"SE","Homicide"],
[7,"SE","Rape"],
[7,"SE","Robbery"],
[7,"SE","Assault"],
[7,"SE","Larceny-Theft"],
[7,"SE","Motor Vehicle Theft"],
[7,"SE","Burglary"],
[7,"SW","Homicide"],
[7,"SW","Rape"],
[7,"SW","Robbery"],
[7,"SW","Assault"],
[7,"SW","Larceny-Theft"],
[7,"SW","Motor Vehicle Theft"],
[7,"SW","Burglary"],
[7,"SW","Homicide"],
[7,"SW","Rape"],
[7,"SW","Robbery"],
[7,"SW","Assault"],
[7,"SW","Larceny-Theft"],
[7,"SW","Motor Vehicle Theft"],
[7,"SW","Burglary"],
[7,"SW","Homicide"],
[7,"SW","Rape"],
[7,"SW","Robbery"],
[7,"SW","Assault"],
[7,"SW","Larceny-Theft"],
[7,"SW","Motor Vehicle Theft"],
[7,"SW","Burglary"],
[7,"SW","Homicide"],
[7,"SW","Rape"],
[7,"SW","Robbery"],
[7,"SW","Assault"],
[7,"SW","Larceny-Theft"],
[7,"SW","Motor Vehicle Theft"],
[7,"SW","Burglary"],
[7,"SW","Homicide"],
[7,"SW","Rape"],
[7,"SW","Robbery"],
[7,"SW","Assault"],
[7,"SW","Larceny-Theft"],
[7,"SW","Motor Vehicle Theft"],
[7,"SW","Burglary"],
[7,"SW","Homicide"],
[7,"SW","Rape"],
[7,"SW","Robbery"],
[7,"SW","Assault"],
[7,"SW","Larceny-Theft"],
[7,"SW","Motor Vehicle Theft"],
[7,"SW","Burglary"],
[6,"E","Larceny-Theft"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"SW","Burglary"],
[6,"SW","Motor Vehicle Theft"],
[6,"SW","Larceny-Theft"],
[6,"SW","Assault"],
[6,"SW","Robbery"],
[6,"SW","Rape"],
[6,"SW","Homicide"],
[6,"SW","Burglary"],
[6,"SW","Motor Vehicle Theft"],
[6,"SW","Larceny-Theft"],
[6,"SW","Assault"],
[6,"SW","Robbery"],
[6,"SW","Rape"],
[6,"SW","Homicide"],
[6,"SW","Burglary"],
[6,"SW","Motor Vehicle Theft"],
[6,"SW","Larceny-Theft"],
[6,"SW","Assault"],
[6,"SW","Robbery"],
[6,"SW","Rape"],
[6,"SW","Homicide"],
[6,"SW","Burglary"],
[6,"SW","Motor Vehicle Theft"],
[6,"SW","Larceny-Theft"],
[6,"SW","Assault"],
[6,"SW","Robbery"],
[6,"SW","Rape"],
[6,"SW","Homicide"],
[6,"SW","Burglary"],
[6,"SW","Motor Vehicle Theft"],
[6,"SW","Larceny-Theft"],
[6,"SW","Assault"],
[6,"SW","Robbery"],
[6,"SW","Rape"],
[6,"SW","Homicide"],
[6,"SW","Burglary"],
[6,"SW","Motor Vehicle Theft"],
[6,"SW","Larceny-Theft"],
[6,"SW","Assault"],
[6,"SW","Robbery"],
[6,"SW","Rape"],
[6,"SW","Homicide"],
[6,"SE","Burglary"],
[6,"SE","Motor Vehicle Theft"],
[6,"SE","Larceny-Theft"],
[6,"SE","Assault"],
[6,"SE","Robbery"],
[6,"SE","Rape"],
[6,"SE","Homicide"],
[6,"SE","Burglary"],
[6,"SE","Motor Vehicle Theft"],
[6,"SE","Larceny-Theft"],
[6,"SE","Assault"],
[6,"SE","Robbery"],
[6,"SE","Rape"],
[6,"SE","Homicide"],
[6,"SE","Burglary"],
[6,"SE","Motor Vehicle Theft"],
[6,"SE","Larceny-Theft"],
[6,"SE","Assault"],
[6,"SE","Robbery"],
[6,"SE","Rape"],
[6,"SE","Homicide"],
[6,"SE","Burglary"],
[6,"SE","Motor Vehicle Theft"],
[6,"SE","Larceny-Theft"],
[6,"SE","Assault"],
[6,"SE","Robbery"],
[6,"SE","Rape"],
[6,"SE","Homicide"],
[6,"SE","Burglary"],
[6,"SE","Motor Vehicle Theft"],
[6,"SE","Larceny-Theft"],
[6,"SE","Assault"],
[6,"SE","Robbery"],
[6,"SE","Rape"],
[6,"SE","Homicide"],
[6,"SE","Burglary"],
[6,"SE","Motor Vehicle Theft"],
[6,"SE","Larceny-Theft"],
[6,"SE","Assault"],
[6,"SE","Robbery"],
[6,"SE","Rape"],
[6,"SE","Homicide"],
[6,"SE","Burglary"],
[6,"SE","Motor Vehicle Theft"],
[6,"SE","Larceny-Theft"],
[6,"SE","Assault"],
[6,"SE","Robbery"],
[6,"SE","Rape"],
[6,"SE","Homicide"],
[6,"SE","Burglary"],
[6,"SE","Motor Vehicle Theft"],
[6,"SE","Larceny-Theft"],
[6,"SE","Assault"],
[6,"SE","Robbery"],
[6,"SE","Rape"],
[6,"SE","Homicide"],
[6,"SE","Burglary"],
[6,"SE","Motor Vehicle Theft"],
[6,"SE","Larceny-Theft"],
[6,"SE","Assault"],
[6,"SE","Robbery"],
[6,"SE","Rape"],
[6,"SE","Homicide"],
[6,"E","Burglary"],
[6,"E","Motor Vehicle Theft"],
[6,"E","Larceny-Theft"],
[6,"E","Assault"],
[6,"E","Robbery"],
[6,"E","Rape"],
[6,"E","Homicide"],
[6,"E","Burglary"],
[6,"E","Motor Vehicle Theft"],
[6,"E","Larceny-Theft"],
[6,"E","Assault"],
[6,"E","Robbery"],
[6,"E","Rape"],
[6,"E","Homicide"],
[6,"E","Burglary"],
[6,"E","Motor Vehicle Theft"],
[6,"E","Larceny-Theft"],
[6,"E","Assault"],
[6,"E","Robbery"],
[6,"E","Rape"],
[6,"E","Homicide"],
[6,"E","Burglary"],
[6,"E","Motor Vehicle Theft"],
[6,"E","Assault"],
[6,"E","Robbery"],
[6,"E","Rape"],
[6,"E","Homicide"],
[6,"E","Burglary"],
[6,"E","Motor Vehicle Theft"],
[6,"E","Larceny-Theft"],
[6,"E","Assault"],
[6,"E","Robbery"],
[6,"E","Rape"],
[6,"E","Homicide"],
[6,"E","Burglary"],
[6,"E","Motor Vehicle Theft"],
[6,"E","Larceny-Theft"],
[6,"E","Assault"],
[6,"E","Robbery"],
[6,"E","Rape"],
[6,"E","Homicide"],
[6,"E","Burglary"],
[6,"E","Motor Vehicle Theft"],
[6,"E","Larceny-Theft"],
[6,"E","Assault"],
[6,"E","Robbery"],
[6,"E","Rape"],
[6,"E","Homicide"],
[6,"E","Burglary"],
[6,"E","Motor Vehicle Theft"],
[6,"E","Larceny-Theft"],
[6,"E","Assault"],
[6,"E","Robbery"],
[6,"E","Rape"],
[6,"E","Homicide"],
[6,"E","Burglary"],
[6,"E","Motor Vehicle Theft"],
[6,"E","Larceny-Theft"],
[6,"E","Assault"],
[6,"E","Robbery"],
[6,"E","Rape"],
[6,"E","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"W","Burglary"],
[6,"W","Motor Vehicle Theft"],
[6,"W","Larceny-Theft"],
[6,"W","Assault"],
[6,"W","Robbery"],
[6,"W","Rape"],
[6,"W","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[6,"N","Burglary"],
[6,"N","Motor Vehicle Theft"],
[6,"N","Larceny-Theft"],
[6,"N","Assault"],
[6,"N","Robbery"],
[6,"N","Rape"],
[6,"N","Homicide"],
[5,"N","Rape"],
[5,"SW","Burglary"],
[5,"SW","Motor Vehicle Theft"],
[5,"SW","Larceny-Theft"],
[5,"SW","Assault"],
[5,"SW","Robbery"],
[5,"SW","Rape"],
[5,"SW","Homicide"],
[5,"SW","Burglary"],
[5,"SW","Motor Vehicle Theft"],
[5,"SW","Larceny-Theft"],
[5,"SW","Assault"],
[5,"SW","Robbery"],
[5,"SW","Rape"],
[5,"SW","Homicide"],
[5,"SW","Burglary"],
[5,"SW","Motor Vehicle Theft"],
[5,"SW","Larceny-Theft"],
[5,"SW","Assault"],
[5,"SW","Robbery"],
[5,"SW","Rape"],
[5,"SW","Homicide"],
[5,"SW","Burglary"],
[5,"SW","Motor Vehicle Theft"],
[5,"SW","Larceny-Theft"],
[5,"SW","Assault"],
[5,"SW","Robbery"],
[5,"SW","Rape"],
[5,"SW","Homicide"],
[5,"SW","Burglary"],
[5,"SW","Motor Vehicle Theft"],
[5,"SW","Larceny-Theft"],
[5,"SW","Assault"],
[5,"SW","Robbery"],
[5,"SW","Rape"],
[5,"SW","Homicide"],
[5,"SW","Burglary"],
[5,"SW","Motor Vehicle Theft"],
[5,"SW","Larceny-Theft"],
[5,"SW","Assault"],
[5,"SW","Robbery"],
[5,"SW","Rape"],
[5,"SW","Homicide"],
[5,"SE","Burglary"],
[5,"SE","Motor Vehicle Theft"],
[5,"SE","Larceny-Theft"],
[5,"SE","Assault"],
[5,"SE","Robbery"],
[5,"SE","Rape"],
[5,"SE","Homicide"],
[5,"SE","Burglary"],
[5,"SE","Motor Vehicle Theft"],
[5,"SE","Larceny-Theft"],
[5,"SE","Assault"],
[5,"SE","Robbery"],
[5,"SE","Rape"],
[5,"SE","Homicide"],
[5,"SE","Burglary"],
[5,"SE","Motor Vehicle Theft"],
[5,"SE","Larceny-Theft"],
[5,"SE","Assault"],
[5,"SE","Robbery"],
[5,"SE","Rape"],
[5,"SE","Homicide"],
[5,"SE","Burglary"],
[5,"SE","Motor Vehicle Theft"],
[5,"SE","Larceny-Theft"],
[5,"SE","Assault"],
[5,"SE","Robbery"],
[5,"SE","Rape"],
[5,"SE","Homicide"],
[5,"SE","Burglary"],
[5,"SE","Motor Vehicle Theft"],
[5,"SE","Larceny-Theft"],
[5,"SE","Assault"],
[5,"SE","Robbery"],
[5,"SE","Rape"],
[5,"SE","Homicide"],
[5,"SE","Burglary"],
[5,"SE","Motor Vehicle Theft"],
[5,"SE","Larceny-Theft"],
[5,"SE","Assault"],
[5,"SE","Robbery"],
[5,"SE","Rape"],
[5,"SE","Homicide"],
[5,"SE","Burglary"],
[5,"SE","Motor Vehicle Theft"],
[5,"SE","Larceny-Theft"],
[5,"SE","Assault"],
[5,"SE","Robbery"],
[5,"SE","Rape"],
[5,"SE","Homicide"],
[5,"SE","Burglary"],
[5,"SE","Motor Vehicle Theft"],
[5,"SE","Larceny-Theft"],
[5,"SE","Assault"],
[5,"SE","Robbery"],
[5,"SE","Rape"],
[5,"SE","Homicide"],
[5,"SE","Burglary"],
[5,"SE","Motor Vehicle Theft"],
[5,"SE","Larceny-Theft"],
[5,"SE","Assault"],
[5,"SE","Robbery"],
[5,"SE","Rape"],
[5,"SE","Homicide"],
[5,"E","Burglary"],
[5,"E","Motor Vehicle Theft"],
[5,"E","Larceny-Theft"],
[5,"E","Assault"],
[5,"E","Robbery"],
[5,"E","Rape"],
[5,"E","Homicide"],
[5,"E","Burglary"],
[5,"E","Motor Vehicle Theft"],
[5,"E","Larceny-Theft"],
[5,"E","Assault"],
[5,"E","Robbery"],
[5,"E","Rape"],
[5,"E","Homicide"],
[5,"E","Burglary"],
[5,"E","Motor Vehicle Theft"],
[5,"E","Larceny-Theft"],
[5,"E","Assault"],
[5,"E","Robbery"],
[5,"E","Rape"],
[5,"E","Homicide"],
[5,"E","Burglary"],
[5,"E","Motor Vehicle Theft"],
[5,"E","Larceny-Theft"],
[5,"E","Assault"],
[5,"E","Robbery"],
[5,"E","Rape"],
[5,"E","Homicide"],
[5,"E","Burglary"],
[5,"E","Motor Vehicle Theft"],
[5,"E","Larceny-Theft"],
[5,"E","Assault"],
[5,"E","Robbery"],
[5,"E","Rape"],
[5,"E","Homicide"],
[5,"E","Burglary"],
[5,"E","Motor Vehicle Theft"],
[5,"E","Larceny-Theft"],
[5,"E","Assault"],
[5,"E","Robbery"],
[5,"E","Rape"],
[5,"E","Homicide"],
[5,"E","Burglary"],
[5,"E","Motor Vehicle Theft"],
[5,"E","Larceny-Theft"],
[5,"E","Assault"],
[5,"E","Robbery"],
[5,"E","Rape"],
[5,"E","Homicide"],
[5,"E","Burglary"],
[5,"E","Motor Vehicle Theft"],
[5,"E","Larceny-Theft"],
[5,"E","Assault"],
[5,"E","Robbery"],
[5,"E","Rape"],
[5,"E","Homicide"],
[5,"E","Burglary"],
[5,"E","Motor Vehicle Theft"],
[5,"E","Larceny-Theft"],
[5,"E","Assault"],
[5,"E","Robbery"],
[5,"E","Rape"],
[5,"E","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"N","Homicide"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"W","Burglary"],
[5,"W","Motor Vehicle Theft"],
[5,"W","Larceny-Theft"],
[5,"W","Assault"],
[5,"W","Robbery"],
[5,"W","Rape"],
[5,"W","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[5,"N","Rape"],
[5,"N","Homicide"],
[5,"N","Burglary"],
[5,"N","Motor Vehicle Theft"],
[5,"N","Larceny-Theft"],
[5,"N","Assault"],
[5,"N","Robbery"],
[4,"SE","Rape"],
[4,"SW","Burglary"],
[4,"SW","Motor Vehicle Theft"],
[4,"SW","Larceny-Theft"],
[4,"SW","Assault"],
[4,"SW","Robbery"],
[4,"SW","Rape"],
[4,"SW","Homicide"],
[4,"SW","Burglary"],
[4,"SW","Motor Vehicle Theft"],
[4,"SW","Larceny-Theft"],
[4,"SW","Assault"],
[4,"SW","Robbery"],
[4,"SW","Rape"],
[4,"SW","Homicide"],
[4,"SW","Burglary"],
[4,"SW","Motor Vehicle Theft"],
[4,"SW","Larceny-Theft"],
[4,"SW","Assault"],
[4,"SW","Robbery"],
[4,"SW","Rape"],
[4,"SW","Homicide"],
[4,"SW","Burglary"],
[4,"SW","Motor Vehicle Theft"],
[4,"SW","Larceny-Theft"],
[4,"SW","Assault"],
[4,"SW","Robbery"],
[4,"SW","Rape"],
[4,"SW","Homicide"],
[4,"SW","Burglary"],
[4,"SW","Motor Vehicle Theft"],
[4,"SW","Larceny-Theft"],
[4,"SW","Assault"],
[4,"SW","Robbery"],
[4,"SW","Rape"],
[4,"SW","Homicide"],
[4,"SW","Burglary"],
[4,"SW","Motor Vehicle Theft"],
[4,"SW","Larceny-Theft"],
[4,"SW","Assault"],
[4,"SW","Robbery"],
[4,"SW","Rape"],
[4,"SW","Homicide"],
[4,"SE","Burglary"],
[4,"SE","Motor Vehicle Theft"],
[4,"SE","Larceny-Theft"],
[4,"SE","Assault"],
[4,"SE","Robbery"],
[4,"SE","Rape"],
[4,"SE","Homicide"],
[4,"SE","Burglary"],
[4,"SE","Motor Vehicle Theft"],
[4,"SE","Larceny-Theft"],
[4,"SE","Assault"],
[4,"SE","Robbery"],
[4,"SE","Rape"],
[4,"SE","Homicide"],
[4,"SE","Burglary"],
[4,"SE","Motor Vehicle Theft"],
[4,"SE","Larceny-Theft"],
[4,"SE","Assault"],
[4,"SE","Robbery"],
[4,"SE","Rape"],
[4,"SE","Homicide"],
[4,"SE","Burglary"],
[4,"SE","Motor Vehicle Theft"],
[4,"SE","Larceny-Theft"],
[4,"SE","Assault"],
[4,"SE","Robbery"],
[4,"SE","Rape"],
[4,"SE","Homicide"],
[4,"SE","Burglary"],
[4,"SE","Motor Vehicle Theft"],
[4,"SE","Larceny-Theft"],
[4,"SE","Assault"],
[4,"SE","Robbery"],
[4,"SE","Rape"],
[4,"SE","Homicide"],
[4,"SE","Burglary"],
[4,"SE","Motor Vehicle Theft"],
[4,"SE","Larceny-Theft"],
[4,"SE","Assault"],
[4,"SE","Robbery"],
[4,"SE","Rape"],
[4,"SE","Homicide"],
[4,"SE","Burglary"],
[4,"SE","Motor Vehicle Theft"],
[4,"SE","Larceny-Theft"],
[4,"SE","Assault"],
[4,"SE","Robbery"],
[4,"SE","Homicide"],
[4,"SE","Burglary"],
[4,"SE","Motor Vehicle Theft"],
[4,"SE","Larceny-Theft"],
[4,"SE","Assault"],
[4,"SE","Robbery"],
[4,"SE","Rape"],
[4,"SE","Homicide"],
[4,"SE","Burglary"],
[4,"SE","Motor Vehicle Theft"],
[4,"SE","Larceny-Theft"],
[4,"SE","Assault"],
[4,"SE","Robbery"],
[4,"SE","Rape"],
[4,"SE","Homicide"],
[4,"E","Burglary"],
[4,"E","Motor Vehicle Theft"],
[4,"E","Larceny-Theft"],
[4,"E","Assault"],
[4,"E","Robbery"],
[4,"E","Rape"],
[4,"E","Homicide"],
[4,"E","Burglary"],
[4,"E","Motor Vehicle Theft"],
[4,"E","Larceny-Theft"],
[4,"E","Assault"],
[4,"E","Robbery"],
[4,"E","Rape"],
[4,"E","Homicide"],
[4,"E","Burglary"],
[4,"E","Motor Vehicle Theft"],
[4,"E","Larceny-Theft"],
[4,"E","Assault"],
[4,"E","Robbery"],
[4,"E","Rape"],
[4,"E","Homicide"],
[4,"E","Burglary"],
[4,"E","Motor Vehicle Theft"],
[4,"E","Larceny-Theft"],
[4,"E","Assault"],
[4,"E","Robbery"],
[4,"E","Rape"],
[4,"E","Homicide"],
[4,"E","Burglary"],
[4,"E","Motor Vehicle Theft"],
[4,"E","Larceny-Theft"],
[4,"E","Assault"],
[4,"E","Robbery"],
[4,"E","Rape"],
[4,"E","Homicide"],
[4,"E","Burglary"],
[4,"E","Motor Vehicle Theft"],
[4,"E","Larceny-Theft"],
[4,"E","Assault"],
[4,"E","Robbery"],
[4,"E","Rape"],
[4,"E","Homicide"],
[4,"E","Burglary"],
[4,"E","Motor Vehicle Theft"],
[4,"E","Larceny-Theft"],
[4,"E","Assault"],
[4,"E","Robbery"],
[4,"E","Rape"],
[4,"E","Homicide"],
[4,"E","Burglary"],
[4,"E","Motor Vehicle Theft"],
[4,"E","Larceny-Theft"],
[4,"E","Assault"],
[4,"E","Robbery"],
[4,"E","Rape"],
[4,"E","Homicide"],
[4,"E","Burglary"],
[4,"E","Motor Vehicle Theft"],
[4,"E","Larceny-Theft"],
[4,"E","Assault"],
[4,"E","Robbery"],
[4,"E","Rape"],
[4,"E","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"W","Burglary"],
[4,"W","Motor Vehicle Theft"],
[4,"W","Larceny-Theft"],
[4,"W","Assault"],
[4,"W","Robbery"],
[4,"W","Rape"],
[4,"W","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[4,"N","Burglary"],
[4,"N","Motor Vehicle Theft"],
[4,"N","Larceny-Theft"],
[4,"N","Assault"],
[4,"N","Robbery"],
[4,"N","Rape"],
[4,"N","Homicide"],
[3,"E","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"SW","Burglary"],
[3,"SW","Motor Vehicle Theft"],
[3,"SW","Larceny-Theft"],
[3,"SW","Assault"],
[3,"SW","Robbery"],
[3,"SW","Rape"],
[3,"SW","Homicide"],
[3,"SW","Burglary"],
[3,"SW","Motor Vehicle Theft"],
[3,"SW","Larceny-Theft"],
[3,"SW","Assault"],
[3,"SW","Robbery"],
[3,"SW","Rape"],
[3,"SW","Homicide"],
[3,"SW","Burglary"],
[3,"SW","Motor Vehicle Theft"],
[3,"SW","Larceny-Theft"],
[3,"SW","Assault"],
[3,"SW","Robbery"],
[3,"SW","Rape"],
[3,"SW","Homicide"],
[3,"SW","Burglary"],
[3,"SW","Motor Vehicle Theft"],
[3,"SW","Larceny-Theft"],
[3,"SW","Assault"],
[3,"SW","Robbery"],
[3,"SW","Rape"],
[3,"SW","Homicide"],
[3,"SW","Burglary"],
[3,"SW","Motor Vehicle Theft"],
[3,"SW","Larceny-Theft"],
[3,"SW","Assault"],
[3,"SW","Robbery"],
[3,"SW","Rape"],
[3,"SW","Homicide"],
[3,"SW","Burglary"],
[3,"SW","Motor Vehicle Theft"],
[3,"SW","Larceny-Theft"],
[3,"SW","Assault"],
[3,"SW","Robbery"],
[3,"SW","Rape"],
[3,"SW","Homicide"],
[3,"SE","Burglary"],
[3,"SE","Motor Vehicle Theft"],
[3,"SE","Larceny-Theft"],
[3,"SE","Assault"],
[3,"SE","Robbery"],
[3,"SE","Rape"],
[3,"SE","Homicide"],
[3,"SE","Burglary"],
[3,"SE","Motor Vehicle Theft"],
[3,"SE","Larceny-Theft"],
[3,"SE","Assault"],
[3,"SE","Robbery"],
[3,"SE","Rape"],
[3,"SE","Homicide"],
[3,"SE","Burglary"],
[3,"SE","Motor Vehicle Theft"],
[3,"SE","Larceny-Theft"],
[3,"SE","Assault"],
[3,"SE","Robbery"],
[3,"SE","Rape"],
[3,"SE","Homicide"],
[3,"SE","Burglary"],
[3,"SE","Motor Vehicle Theft"],
[3,"SE","Larceny-Theft"],
[3,"SE","Assault"],
[3,"SE","Robbery"],
[3,"SE","Rape"],
[3,"SE","Homicide"],
[3,"SE","Burglary"],
[3,"SE","Motor Vehicle Theft"],
[3,"SE","Larceny-Theft"],
[3,"SE","Assault"],
[3,"SE","Robbery"],
[3,"SE","Rape"],
[3,"SE","Homicide"],
[3,"SE","Burglary"],
[3,"SE","Motor Vehicle Theft"],
[3,"SE","Larceny-Theft"],
[3,"SE","Assault"],
[3,"SE","Robbery"],
[3,"SE","Rape"],
[3,"SE","Homicide"],
[3,"SE","Burglary"],
[3,"SE","Motor Vehicle Theft"],
[3,"SE","Larceny-Theft"],
[3,"SE","Assault"],
[3,"SE","Robbery"],
[3,"SE","Rape"],
[3,"SE","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"N","Burglary"],
[3,"N","Motor Vehicle Theft"],
[3,"N","Larceny-Theft"],
[3,"N","Assault"],
[3,"N","Robbery"],
[3,"N","Rape"],
[3,"N","Homicide"],
[3,"SE","Burglary"],
[3,"SE","Motor Vehicle Theft"],
[3,"SE","Larceny-Theft"],
[3,"SE","Assault"],
[3,"SE","Robbery"],
[3,"SE","Rape"],
[3,"SE","Homicide"],
[3,"SE","Burglary"],
[3,"SE","Motor Vehicle Theft"],
[3,"SE","Larceny-Theft"],
[3,"SE","Assault"],
[3,"SE","Robbery"],
[3,"SE","Rape"],
[3,"SE","Homicide"],
[3,"E","Burglary"],
[3,"E","Motor Vehicle Theft"],
[3,"E","Larceny-Theft"],
[3,"E","Assault"],
[3,"E","Robbery"],
[3,"E","Rape"],
[3,"E","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"E","Burglary"],
[3,"E","Motor Vehicle Theft"],
[3,"E","Larceny-Theft"],
[3,"E","Assault"],
[3,"E","Robbery"],
[3,"E","Rape"],
[3,"E","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"E","Burglary"],
[3,"E","Motor Vehicle Theft"],
[3,"E","Larceny-Theft"],
[3,"E","Assault"],
[3,"E","Robbery"],
[3,"E","Rape"],
[3,"E","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"E","Burglary"],
[3,"E","Motor Vehicle Theft"],
[3,"E","Larceny-Theft"],
[3,"E","Assault"],
[3,"E","Robbery"],
[3,"E","Rape"],
[3,"E","Homicide"],
[3,"E","Burglary"],
[3,"E","Motor Vehicle Theft"],
[3,"E","Larceny-Theft"],
[3,"E","Assault"],
[3,"E","Robbery"],
[3,"E","Rape"],
[3,"E","Homicide"],
[3,"E","Burglary"],
[3,"E","Motor Vehicle Theft"],
[3,"E","Larceny-Theft"],
[3,"E","Assault"],
[3,"E","Robbery"],
[3,"E","Rape"],
[3,"E","Homicide"],
[3,"E","Burglary"],
[3,"E","Motor Vehicle Theft"],
[3,"E","Larceny-Theft"],
[3,"E","Assault"],
[3,"E","Robbery"],
[3,"E","Rape"],
[3,"E","Homicide"],
[3,"W","Burglary"],
[3,"W","Motor Vehicle Theft"],
[3,"W","Larceny-Theft"],
[3,"W","Assault"],
[3,"W","Robbery"],
[3,"W","Rape"],
[3,"W","Homicide"],
[3,"E","Burglary"],
[3,"E","Motor Vehicle Theft"],
[3,"E","Larceny-Theft"],
[3,"E","Assault"],
[3,"E","Robbery"],
[3,"E","Rape"],
[3,"E","Homicide"],
[3,"E","Burglary"],
[3,"E","Motor Vehicle Theft"],
[3,"E","Larceny-Theft"],
[3,"E","Assault"],
[3,"E","Robbery"],
[3,"E","Rape"],
[2,"E","Larceny-Theft"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"SW","Burglary"],
[2,"SW","Motor Vehicle Theft"],
[2,"SW","Larceny-Theft"],
[2,"SW","Assault"],
[2,"SW","Robbery"],
[2,"SW","Rape"],
[2,"SW","Homicide"],
[2,"SW","Burglary"],
[2,"SW","Motor Vehicle Theft"],
[2,"SW","Larceny-Theft"],
[2,"SW","Assault"],
[2,"SW","Robbery"],
[2,"SW","Rape"],
[2,"SW","Homicide"],
[2,"SW","Burglary"],
[2,"SW","Motor Vehicle Theft"],
[2,"SW","Larceny-Theft"],
[2,"SW","Assault"],
[2,"SW","Robbery"],
[2,"SW","Rape"],
[2,"SW","Homicide"],
[2,"SW","Burglary"],
[2,"SW","Motor Vehicle Theft"],
[2,"SW","Larceny-Theft"],
[2,"SW","Assault"],
[2,"SW","Robbery"],
[2,"SW","Rape"],
[2,"SW","Homicide"],
[2,"SW","Burglary"],
[2,"SW","Motor Vehicle Theft"],
[2,"SW","Larceny-Theft"],
[2,"SW","Assault"],
[2,"SW","Robbery"],
[2,"SW","Rape"],
[2,"SW","Homicide"],
[2,"SW","Burglary"],
[2,"SW","Motor Vehicle Theft"],
[2,"SW","Larceny-Theft"],
[2,"SW","Assault"],
[2,"SW","Robbery"],
[2,"SW","Rape"],
[2,"SW","Homicide"],
[2,"SE","Burglary"],
[2,"SE","Motor Vehicle Theft"],
[2,"SE","Larceny-Theft"],
[2,"SE","Assault"],
[2,"SE","Robbery"],
[2,"SE","Rape"],
[2,"SE","Homicide"],
[2,"SE","Burglary"],
[2,"SE","Motor Vehicle Theft"],
[2,"SE","Larceny-Theft"],
[2,"SE","Assault"],
[2,"SE","Robbery"],
[2,"SE","Rape"],
[2,"SE","Homicide"],
[2,"SE","Burglary"],
[2,"SE","Motor Vehicle Theft"],
[2,"SE","Larceny-Theft"],
[2,"SE","Assault"],
[2,"SE","Robbery"],
[2,"SE","Rape"],
[2,"SE","Homicide"],
[2,"SE","Burglary"],
[2,"SE","Motor Vehicle Theft"],
[2,"SE","Larceny-Theft"],
[2,"SE","Assault"],
[2,"SE","Robbery"],
[2,"SE","Rape"],
[2,"SE","Homicide"],
[2,"SE","Burglary"],
[2,"SE","Motor Vehicle Theft"],
[2,"SE","Larceny-Theft"],
[2,"SE","Assault"],
[2,"SE","Robbery"],
[2,"SE","Rape"],
[2,"SE","Homicide"],
[2,"SE","Burglary"],
[2,"SE","Motor Vehicle Theft"],
[2,"SE","Larceny-Theft"],
[2,"SE","Assault"],
[2,"SE","Robbery"],
[2,"SE","Rape"],
[2,"SE","Homicide"],
[2,"SE","Burglary"],
[2,"SE","Motor Vehicle Theft"],
[2,"SE","Larceny-Theft"],
[2,"SE","Assault"],
[2,"SE","Robbery"],
[2,"SE","Rape"],
[2,"SE","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"N","Burglary"],
[2,"N","Motor Vehicle Theft"],
[2,"N","Larceny-Theft"],
[2,"N","Assault"],
[2,"N","Robbery"],
[2,"N","Rape"],
[2,"N","Homicide"],
[2,"SE","Burglary"],
[2,"SE","Motor Vehicle Theft"],
[2,"SE","Larceny-Theft"],
[2,"SE","Assault"],
[2,"SE","Robbery"],
[2,"SE","Rape"],
[2,"SE","Homicide"],
[2,"SE","Burglary"],
[2,"SE","Motor Vehicle Theft"],
[2,"SE","Larceny-Theft"],
[2,"SE","Assault"],
[2,"SE","Robbery"],
[2,"SE","Rape"],
[2,"SE","Homicide"],
[2,"E","Burglary"],
[2,"E","Motor Vehicle Theft"],
[2,"E","Larceny-Theft"],
[2,"E","Assault"],
[2,"E","Robbery"],
[2,"E","Rape"],
[2,"E","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"E","Burglary"],
[2,"E","Motor Vehicle Theft"],
[2,"E","Larceny-Theft"],
[2,"E","Assault"],
[2,"E","Robbery"],
[2,"E","Rape"],
[2,"E","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"E","Burglary"],
[2,"E","Motor Vehicle Theft"],
[2,"E","Larceny-Theft"],
[2,"E","Assault"],
[2,"E","Robbery"],
[2,"E","Rape"],
[2,"E","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"E","Burglary"],
[2,"E","Motor Vehicle Theft"],
[2,"E","Assault"],
[2,"E","Robbery"],
[2,"E","Rape"],
[2,"E","Homicide"],
[2,"E","Burglary"],
[2,"E","Motor Vehicle Theft"],
[2,"E","Larceny-Theft"],
[2,"E","Assault"],
[2,"E","Robbery"],
[2,"E","Rape"],
[2,"E","Homicide"],
[2,"E","Burglary"],
[2,"E","Motor Vehicle Theft"],
[2,"E","Larceny-Theft"],
[2,"E","Assault"],
[2,"E","Robbery"],
[2,"E","Rape"],
[2,"E","Homicide"],
[2,"E","Burglary"],
[2,"E","Motor Vehicle Theft"],
[2,"E","Larceny-Theft"],
[2,"E","Assault"],
[2,"E","Robbery"],
[2,"E","Rape"],
[2,"E","Homicide"],
[2,"W","Burglary"],
[2,"W","Motor Vehicle Theft"],
[2,"W","Larceny-Theft"],
[2,"W","Assault"],
[2,"W","Robbery"],
[2,"W","Rape"],
[2,"W","Homicide"],
[2,"E","Burglary"],
[2,"E","Motor Vehicle Theft"],
[2,"E","Larceny-Theft"],
[2,"E","Assault"],
[2,"E","Robbery"],
[2,"E","Rape"],
[2,"E","Homicide"],
[2,"E","Burglary"],
[2,"E","Motor Vehicle Theft"],
[2,"E","Larceny-Theft"],
[2,"E","Assault"],
[2,"E","Robbery"],
[2,"E","Rape"],
[2,"E","Homicide"],
[1,"W","Motor Vehicle Theft"],
[1,"E","Rape"],
[1,"E","Robbery"],
[1,"E","Assault"],
[1,"E","Larceny-Theft"],
[1,"E","Motor Vehicle Theft"],
[1,"E","Burglary"],
[1,"E","Homicide"],
[1,"E","Rape"],
[1,"E","Robbery"],
[1,"E","Assault"],
[1,"E","Larceny-Theft"],
[1,"E","Motor Vehicle Theft"],
[1,"E","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"W","Burglary"],
[1,"E","Homicide"],
[1,"E","Rape"],
[1,"E","Robbery"],
[1,"E","Assault"],
[1,"E","Larceny-Theft"],
[1,"E","Motor Vehicle Theft"],
[1,"E","Burglary"],
[1,"E","Homicide"],
[1,"E","Rape"],
[1,"E","Robbery"],
[1,"E","Assault"],
[1,"E","Larceny-Theft"],
[1,"E","Motor Vehicle Theft"],
[1,"E","Burglary"],
[1,"E","Homicide"],
[1,"E","Rape"],
[1,"E","Robbery"],
[1,"E","Assault"],
[1,"E","Larceny-Theft"],
[1,"E","Motor Vehicle Theft"],
[1,"E","Burglary"],
[1,"E","Homicide"],
[1,"E","Rape"],
[1,"E","Robbery"],
[1,"E","Assault"],
[1,"E","Larceny-Theft"],
[1,"E","Motor Vehicle Theft"],
[1,"E","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"W","Burglary"],
[1,"E","Homicide"],
[1,"E","Rape"],
[1,"E","Robbery"],
[1,"E","Assault"],
[1,"E","Larceny-Theft"],
[1,"E","Motor Vehicle Theft"],
[1,"E","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"W","Burglary"],
[1,"E","Homicide"],
[1,"E","Rape"],
[1,"E","Robbery"],
[1,"E","Assault"],
[1,"E","Larceny-Theft"],
[1,"E","Motor Vehicle Theft"],
[1,"E","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"W","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"E","Homicide"],
[1,"W","Burglary"],
[1,"E","Homicide"],
[1,"E","Rape"],
[1,"E","Robbery"],
[1,"E","Assault"],
[1,"E","Larceny-Theft"],
[1,"E","Motor Vehicle Theft"],
[1,"E","Burglary"],
[1,"SE","Homicide"],
[1,"SE","Rape"],
[1,"SE","Robbery"],
[1,"SE","Assault"],
[1,"SE","Larceny-Theft"],
[1,"SE","Motor Vehicle Theft"],
[1,"SE","Burglary"],
[1,"SE","Homicide"],
[1,"SE","Rape"],
[1,"SE","Robbery"],
[1,"SE","Assault"],
[1,"SE","Larceny-Theft"],
[1,"SE","Motor Vehicle Theft"],
[1,"SE","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"N","Homicide"],
[1,"N","Rape"],
[1,"N","Robbery"],
[1,"N","Assault"],
[1,"N","Larceny-Theft"],
[1,"N","Motor Vehicle Theft"],
[1,"N","Burglary"],
[1,"SE","Homicide"],
[1,"SE","Rape"],
[1,"SE","Robbery"],
[1,"SE","Assault"],
[1,"SE","Larceny-Theft"],
[1,"SE","Motor Vehicle Theft"],
[1,"SE","Burglary"],
[1,"SE","Homicide"],
[1,"SE","Rape"],
[1,"SE","Robbery"],
[1,"SE","Assault"],
[1,"SE","Larceny-Theft"],
[1,"SE","Motor Vehicle Theft"],
[1,"SE","Burglary"],
[1,"SE","Homicide"],
[1,"SE","Rape"],
[1,"SE","Robbery"],
[1,"SE","Assault"],
[1,"SE","Larceny-Theft"],
[1,"SE","Motor Vehicle Theft"],
[1,"SE","Burglary"],
[1,"SE","Homicide"],
[1,"SE","Rape"],
[1,"SE","Robbery"],
[1,"SE","Assault"],
[1,"SE","Larceny-Theft"],
[1,"SE","Motor Vehicle Theft"],
[1,"SE","Burglary"],
[1,"SE","Homicide"],
[1,"SE","Rape"],
[1,"SE","Robbery"],
[1,"SE","Assault"],
[1,"SE","Larceny-Theft"],
[1,"SE","Motor Vehicle Theft"],
[1,"SE","Burglary"],
[1,"SE","Homicide"],
[1,"SE","Rape"],
[1,"SE","Robbery"],
[1,"SE","Assault"],
[1,"SE","Larceny-Theft"],
[1,"SE","Motor Vehicle Theft"],
[1,"SE","Burglary"],
[1,"SE","Homicide"],
[1,"SE","Rape"],
[1,"SE","Robbery"],
[1,"SE","Assault"],
[1,"SE","Larceny-Theft"],
[1,"SE","Motor Vehicle Theft"],
[1,"SE","Burglary"],
[1,"SW","Homicide"],
[1,"SW","Rape"],
[1,"SW","Robbery"],
[1,"SW","Assault"],
[1,"SW","Larceny-Theft"],
[1,"SW","Motor Vehicle Theft"],
[1,"SW","Burglary"],
[1,"SW","Homicide"],
[1,"SW","Rape"],
[1,"SW","Robbery"],
[1,"SW","Assault"],
[1,"SW","Larceny-Theft"],
[1,"SW","Motor Vehicle Theft"],
[1,"SW","Burglary"],
[1,"SW","Homicide"],
[1,"SW","Rape"],
[1,"SW","Robbery"],
[1,"SW","Assault"],
[1,"SW","Larceny-Theft"],
[1,"SW","Motor Vehicle Theft"],
[1,"SW","Burglary"],
[1,"SW","Homicide"],
[1,"SW","Rape"],
[1,"SW","Robbery"],
[1,"SW","Assault"],
[1,"SW","Larceny-Theft"],
[1,"SW","Motor Vehicle Theft"],
[1,"SW","Burglary"],
[1,"SW","Homicide"],
[1,"SW","Rape"],
[1,"SW","Robbery"],
[1,"SW","Assault"],
[1,"SW","Larceny-Theft"],
[1,"SW","Motor Vehicle Theft"],
[1,"SW","Burglary"],
[1,"SW","Homicide"],
[1,"SW","Rape"],
[1,"SW","Robbery"],
[1,"SW","Assault"],
[1,"SW","Larceny-Theft"],
[1,"SW","Motor Vehicle Theft"],
[1,"SW","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Burglary"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"W","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"W","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"W","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"W","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"W","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"],
[1,"W","Motor Vehicle Theft"],
[1,"W","Burglary"],
[1,"W","Homicide"],
[1,"W","Rape"],
[1,"W","Robbery"],
[1,"W","Assault"],
[1,"W","Larceny-Theft"]
];
